/*
 * File: leg_conv_ljw.c
 *
 * MATLAB Coder version            : 5.6
 * C/C++ source code generated on  : 28-Aug-2023 15:18:24
 */

/* Include Files */
#include "leg_conv_ljw.h"
#include <math.h>

/* Function Definitions */
/*
 * LEG_CONV_LJW
 *     T = LEG_CONV_LJW(F,Tp,L1,L2,L3,L4,L5,PHI1,PHI4)
 *
 * Arguments    : float F
 *                float Tp
 *                float l1
 *                float l2
 *                float l3
 *                float l4
 *                float l5
 *                float phi1
 *                float phi4
 *                float T[2]
 * Return Type  : void
 */
void leg_conv(float F, float Tp, float l1, float l2, float l3, float l4,
// void leg_conv_ljw(float F, float Tp, float l1, float l2, float l3, float l4,
              float l5, float phi1, float phi4, float T[2])
{
  float T_tmp;
  float a_tmp;
  float b_T_tmp;
  float b_a_tmp;
  float c_a_tmp;
  float t104_tmp;
  float t105_tmp;
  float t117_tmp;
  float t143_tmp;
  float t144_tmp;
  float t145_tmp;
  float t189;
  float t19_tmp;
  float t23_tmp;
  float t24_tmp;
  float t25_tmp;
  float t26_tmp;
  float t28_tmp;
  float t61_tmp;
  float t62_tmp;
  float t63;
  float t64;
  float t93_tmp;
  float t94_tmp;
  float t95_tmp;
  /*     This function was generated by the Symbolic Math Toolbox version 9.3.
   */
  /*     28-Aug-2023 22:55:56 */
  t19_tmp = l2 * l2;
  t28_tmp = l5 / 2.0F;
  t23_tmp = l1 * cosf(phi1);
  t24_tmp = l4 * cosf(phi4);
  t25_tmp = l1 * sinf(phi1);
  t26_tmp = l4 * sinf(phi4);
  t61_tmp = t25_tmp - t26_tmp;
  t62_tmp = (l5 + t24_tmp) - t23_tmp;
  t63 = t61_tmp * t61_tmp;
  t64 = t62_tmp * t62_tmp;
  t93_tmp = t23_tmp * t61_tmp * 2.0F + t25_tmp * t62_tmp * 2.0F;
  t94_tmp = t24_tmp * t61_tmp * 2.0F + t26_tmp * t62_tmp * 2.0F;
  t95_tmp = ((t19_tmp - l3 * l3) + t63) + t64;
  t104_tmp = 1.0F / (l2 * t62_tmp * 2.0F + t95_tmp);
  t105_tmp = t104_tmp * t104_tmp;
  t63 =
      sqrtf((t19_tmp * t63 * 4.0F + t19_tmp * t64 * 4.0F) - t95_tmp * t95_tmp);
  t117_tmp = 1.0F / t63;
  a_tmp = l2 * t61_tmp * 2.0F - t63;
  t63 = atanf(-t104_tmp * a_tmp) * 2.0F;
  t145_tmp = 1.0F / (t105_tmp * (a_tmp * a_tmp) + 1.0F);
  t143_tmp = l2 * cosf(t63);
  t144_tmp = l2 * sinf(t63);
  b_a_tmp = t25_tmp + t144_tmp;
  c_a_tmp = (t23_tmp - t28_tmp) + t143_tmp;
  t63 = (t28_tmp - t23_tmp) - t143_tmp;
  t64 = t63 * t63;
  t189 = 1.0F / t63;
  t63 = b_a_tmp * b_a_tmp;
  T_tmp = -(l2 * t25_tmp * 2.0F + t93_tmp) * t105_tmp * a_tmp +
          t104_tmp *
              (l2 * t23_tmp * 2.0F - t117_tmp *
                                         ((t19_tmp * t23_tmp * t61_tmp * 8.0F +
                                           t19_tmp * t25_tmp * t62_tmp * 8.0F) -
                                          t93_tmp * t95_tmp * 2.0F) /
                                         2.0F);
  b_T_tmp = F * (1.0F / sqrtf(t63 + c_a_tmp * c_a_tmp));
  t28_tmp = Tp * t64 * (1.0F / (t63 + t64));
  t93_tmp = -t143_tmp * t145_tmp;
  t63 = b_a_tmp * (1.0F / t64);
  t64 = -t144_tmp * t145_tmp;
  T[0] = b_T_tmp *
             (b_a_tmp * (t23_tmp - t143_tmp * t145_tmp * T_tmp * 2.0F) * 2.0F -
              c_a_tmp * (t25_tmp - t144_tmp * t145_tmp * T_tmp * 2.0F) * 2.0F) /
             2.0F -
         t28_tmp * (t189 * (t23_tmp + t93_tmp * T_tmp * 2.0F) -
                    t63 * (t25_tmp + t64 * T_tmp * 2.0F));
  T_tmp = -(l2 * t26_tmp * 2.0F + t94_tmp) * t105_tmp * a_tmp +
          t104_tmp *
              (l2 * t24_tmp * 2.0F - t117_tmp *
                                         ((t19_tmp * t24_tmp * t61_tmp * 8.0F +
                                           t19_tmp * t26_tmp * t62_tmp * 8.0F) -
                                          t94_tmp * t95_tmp * 2.0F) /
                                         2.0F);
  T[1] = b_T_tmp *
             (t143_tmp * b_a_tmp * t145_tmp * T_tmp * 4.0F -
              t144_tmp * c_a_tmp * t145_tmp * T_tmp * 4.0F) /
             2.0F -
         t28_tmp * (t189 * (0.0F - t93_tmp * T_tmp * 2.0F) +
                    t63 * (t64 * T_tmp * 2.0F));
}

/*
 * File trailer for leg_conv_ljw.c
 *
 * [EOF]
 */
