/*
 * File: leg_pos.c
 *
 * MATLAB Coder version            : 5.5
 * C/C++ source code generated on  : 27-Jan-2023 19:41:46
 */

/* Include Files */
#include "leg_pos.h"
#include <math.h>

/* Function Definitions */
/*
 * LEG_POS
 *     POS = LEG_POS(PHI1,PHI4)
 *
 * Arguments    : float phi1
 *                float phi4
 *                float pos[2]
 * Return Type  : void
 */
// void leg_pos(float phi1, float phi4, float pos[2])
// {
//   float a;
//   float b_a;
//   float t14;
//   float t15;
//   float t2;
//   float t3;
//   float t4;
//   float t5;
//   float t6;
//   float t8_tmp;
//   /*     This function was generated by the Symbolic Math Toolbox version 9.2.
//    */
//   /*     27-Jan-2023 19:36:58 */
//   t2 = cosf(phi1);
//   t3 = cosf(phi4);
//   t4 = sinf(phi1);
//   t5 = sinf(phi4);
//   t6 = t2 / 20.0F;
//   t8_tmp = t4 / 20.0F;
//   t14 = t4 * 0.0105F;
//   t15 = t5 * 0.0105F;
//   t5 = t8_tmp - t5 / 20.0F;
//   a = (t3 / 20.0F - t6) + 0.06F;
//   b_a = t14 - t15;
//   t4 = t3 * 0.0105F - t2 * 0.0105F;
//   t5 = t5 * t5 + a * a;
//   t4 = atanf(1.0F / ((t4 + 0.0126F) + t5) *
//              ((t15 - t14) +
//               sqrtf((b_a * b_a + (t4 + 0.0126F) * (t4 + 0.0126F)) - t5 * t5))) *
//        2.0F;
//   t5 = t8_tmp + sinf(t4) * 0.105F;
//   t4 = (t6 + cosf(t4) * 0.105F) - 0.03F;
//   pos[0] = sqrtf(t5 * t5 + t4 * t4);
//   pos[1] = atan2f(t5, t4);
// }

/**
  * @brief          腿部姿态计算
  * @note           原来的函数由MATLAB直接生成，可能把关节长度直接融合进去了，中找不到关节长度的参数，不具备普遍性，重新按照韭菜的文章写一个
  * @note           参数定义完全按照韭菜的文章,l5为电机轴间距
  * @author         小企鹅
  */
void leg_pos(float phi1, float phi4, float pos[2], 
             float l1, float l2, float l3, float l4, float l5)
{
  float x_B = l1*cosf(phi1);
  float y_B = l1*sinf(phi1);
  float x_D = l4*cosf(phi4)+l5;
  float y_D = l4*sinf(phi4);
  float l_BD = sqrtf(pow((x_B-x_D),2)+pow((y_B-y_D),2));
  float A0 = 2*l2*(x_D-x_B);
  float B0 = 2*l2*(y_D-y_B);
  float C0 = pow(l2,2)+pow(l_BD,2)-pow(l3,2);
  float phi2 = 2*atan2f((B0+sqrtf(pow(A0,2)+pow(B0,2)-pow(C0,2))),(A0+C0));
  float x_C = x_B+l2*cosf(phi2);
  float y_C = y_B+l2*sinf(phi2);
  
  pos[0] = sqrtf(pow((x_C-l5/2),2)+pow(y_C,2));
  pos[1] = atan2f(y_C,(x_C-l5/2));
}

/*
 * File trailer for leg_pos.c
 *
 * [EOF]
 */
