/*
 * File: leg_spd_ljw.c
 *
 * MATLAB Coder version            : 5.6
 * C/C++ source code generated on  : 28-Aug-2023 15:18:20
 */

/* Include Files */
#include "leg_spd_ljw.h"
#include <math.h>

/* Function Definitions */
/*
 * LEG_SPD_LJW
 *     SPD = LEG_SPD_LJW(DPHI1,DPHI4,L1,L2,L3,L4,L5,PHI1,PHI4)
 *
 * Arguments    : float dphi1
 *                float dphi4
 *                float l1
 *                float l2
 *                float l3
 *                float l4
 *                float l5
 *                float phi1
 *                float phi4
 *                float spd[2]
 * Return Type  : void
 */
void leg_spd(float dphi1, float dphi4, float l1, float l2, float l3,
// void leg_spd_ljw(float dphi1, float dphi4, float l1, float l2, float l3,
             float l4, float l5, float phi1, float phi4, float spd[2])
{
  float a_tmp;
  float spd_tmp;
  float t10;
  float t104;
  float t105;
  float t106;
  float t11;
  float t111;
  float t12;
  float t13;
  float t15_tmp;
  float t33;
  float t34;
  float t35;
  float t36;
  float t50;
  float t51;
  float t52;
  float t58;
  float t59;
  float t66;
  float t78;
  float t79;
  float t8;
  float t80;
  float t86_tmp;
  float t88;
  /*     This function was generated by the Symbolic Math Toolbox version 9.3.
   */
  /*     28-Aug-2023 22:55:55 */
  t8 = l2 * l2;
  t15_tmp = l5 / 2.0F;
  t10 = l1 * cosf(phi1);
  t11 = l4 * cosf(phi4);
  t12 = l1 * sinf(phi1);
  t13 = l4 * sinf(phi4);
  t33 = t12 - t13;
  t34 = (l5 + t11) - t10;
  t35 = t33 * t33;
  t36 = t34 * t34;
  t50 = t10 * t33 * 2.0F + t12 * t34 * 2.0F;
  t51 = t11 * t33 * 2.0F + t13 * t34 * 2.0F;
  t52 = ((t8 - l3 * l3) + t35) + t36;
  t58 = 1.0F / (l2 * t34 * 2.0F + t52);
  t59 = t58 * t58;
  t35 = sqrtf((t8 * t35 * 4.0F + t8 * t36 * 4.0F) - t52 * t52);
  t66 = 1.0F / t35;
  a_tmp = l2 * t33 * 2.0F - t35;
  t35 = atanf(-t58 * a_tmp) * 2.0F;
  t80 = 1.0F / (t59 * (a_tmp * a_tmp) + 1.0F);
  t78 = l2 * cosf(t35);
  t79 = l2 * sinf(t35);
  t86_tmp = t12 + t79;
  t88 = (t10 - t15_tmp) + t78;
  t35 = (t15_tmp - t10) - t78;
  t36 = t86_tmp * t86_tmp;
  t104 = 1.0F / sqrtf(t36 + t88 * t88);
  t105 = t35 * t35;
  t106 = 1.0F / t35;
  t111 = 1.0F / (t36 + t105);
  t15_tmp = -(l2 * t12 * 2.0F + t50) * t59 * a_tmp +
            t58 * (l2 * t10 * 2.0F -
                   t66 *
                       ((t8 * t10 * t33 * 8.0F + t8 * t12 * t34 * 8.0F) -
                        t50 * t52 * 2.0F) /
                       2.0F);
  t50 = t78 * t80;
  spd_tmp = t79 * t80;
  t36 = -(l2 * t13 * 2.0F + t51) * t59 * a_tmp +
        t58 * (l2 * t11 * 2.0F -
               t66 *
                   ((t8 * t11 * t33 * 8.0F + t8 * t13 * t34 * 8.0F) -
                    t51 * t52 * 2.0F) /
                   2.0F);
  spd[0] = dphi1 * t104 *
               (t86_tmp * (t10 - t50 * t15_tmp * 2.0F) * 2.0F -
                t88 * (t12 - spd_tmp * t15_tmp * 2.0F) * 2.0F) /
               2.0F +
           dphi4 * t104 *
               (t50 * t86_tmp * t36 * 4.0F - spd_tmp * t88 * t36 * 4.0F) / 2.0F;
  t50 = -t78 * t80;
  spd_tmp = t86_tmp * (1.0F / t105);
  t35 = -t79 * t80;
  spd[1] =
      -dphi4 * t105 * t111 *
          (t106 * (0.0F - t50 * t36 * 2.0F) + spd_tmp * (t35 * t36 * 2.0F)) -
      dphi1 * t105 * t111 *
          (t106 * (t10 + t50 * t15_tmp * 2.0F) -
           spd_tmp * (t12 + t35 * t15_tmp * 2.0F));
}

/*
 * File trailer for leg_spd_ljw.c
 *
 * [EOF]
 */
