function pos = JointPos(l0,phi0)
%JointPos
%    POS = JointPos(L0,PHI0)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    2023-10-21 00:16:27

t2 = cos(phi0);
t3 = l0.^2;
t4 = l0.*t2.*(1.9e+1./2.0e+2);
t5 = -t4;
t6 = t3+t4+2.25625e-3;
t7 = t3+t5+2.25625e-3;
t8 = 1.0./sqrt(t6);
t9 = 1.0./sqrt(t7);
mt1 = [acos(t8.*(t4+4.5125e-3).*(2.0e+2./1.9e+1))+acos(t8.*(t3+t4-2.481875e-2).*(1.0e+2./1.9e+1))];
mt2 = [pi.*2.0-acos(t9.*(t4-4.5125e-3).*(2.0e+2./1.9e+1))-acos(t9.*(-t3+t4+2.481875e-2).*(1.0e+2./1.9e+1))];
pos = [mt1;mt2];
end
