function limit = LegAngleLimit(l0)
%LegAngleLimit
%    LIMIT = LegAngleLimit(L0)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    2023-11-08 01:13:31

t2 = l0.^2;
t3 = 1.0./l0;
t4 = t2-7.896875e-2;
t5 = t3.*t4.*(2.0e+2./1.9e+1);
t6 = acos(t5);
limit = [-t6+pi;t6];
end
