/*
 * File: LegConv.c
 *
 * MATLAB Coder version            : 23.2
 * C/C++ source code generated on  : 02-Oct-2023 13:14:02
 */

/* Include Files */
#include "LegConv.h"
#include <math.h>

/* Function Definitions */
/*
 * LegConv
 *     T = LegConv(F,Tp,PHI1,PHI4)
 *
 * Arguments    : float F
 *                float Tp
 *                float phi1
 *                float phi4
 *                float T[2]
 * Return Type  : void
 */
void LegConv(float F, float Tp, float phi1, float phi4, float T[2])
{
  float t104;
  float t106_tmp;
  float t108_tmp;
  float t120_tmp;
  float t123_tmp;
  float t124_tmp;
  float t131_tmp;
  float t16_tmp;
  float t174;
  float t175;
  float t18_tmp;
  float t33_tmp;
  float t34_tmp;
  float t35_tmp;
  float t36_tmp;
  float t51_tmp;
  float t54_tmp;
  float t5_tmp;
  float t66_tmp;
  float t75_tmp;
  float t7_tmp;
  float t81_tmp;
  float t82_tmp;
  float t91_tmp;
  /*     This function was generated by the Symbolic Math Toolbox version 23.2.
   */
  /*     02-Oct-2023 20:34:36 */
  t174 = cosf(phi1);
  t5_tmp = cosf(phi4);
  t175 = sinf(phi1);
  t7_tmp = sinf(phi4);
  t16_tmp = t174 * 0.085F;
  t18_tmp = t175 * 0.085F;
  t33_tmp = t174 * 0.02805F;
  t34_tmp = t5_tmp * 0.02805F;
  t35_tmp = t175 * 0.02805F;
  t36_tmp = t7_tmp * 0.02805F;
  t104 = t18_tmp - t7_tmp * 0.085F;
  t51_tmp = (t5_tmp * 0.085F - t16_tmp) + 0.095F;
  t54_tmp = t35_tmp - t36_tmp;
  t66_tmp = (t34_tmp - t33_tmp) + 0.03135F;
  t75_tmp = t104 * t104 + t51_tmp * t51_tmp;
  t81_tmp = t174 * t104 * 0.17F + t175 * t51_tmp * 0.17F;
  t82_tmp = t5_tmp * t104 * 0.17F + t7_tmp * t51_tmp * 0.17F;
  t51_tmp = 1.0F / (t66_tmp + t75_tmp);
  t91_tmp = t51_tmp * t51_tmp;
  t104 = sqrtf((t54_tmp * t54_tmp + t66_tmp * t66_tmp) - t75_tmp * t75_tmp);
  t106_tmp = 1.0F / t104;
  t108_tmp = (t36_tmp - t35_tmp) + t104;
  t120_tmp = atanf(t51_tmp * t108_tmp) * 2.0F;
  t123_tmp = cosf(t120_tmp);
  t124_tmp = sinf(t120_tmp);
  t131_tmp = 1.0F / (t91_tmp * (t108_tmp * t108_tmp) + 1.0F);
  t120_tmp =
      (t35_tmp + t81_tmp) * t91_tmp * t108_tmp +
      t51_tmp * (t33_tmp -
                 t106_tmp *
                     ((t174 * t54_tmp * 0.0561F + t175 * t66_tmp * 0.0561F) -
                      t75_tmp * t81_tmp * 2.0F) /
                     2.0F);
  t33_tmp = (t36_tmp + t82_tmp) * t91_tmp * t108_tmp +
            t51_tmp * (t34_tmp - t106_tmp *
                                     ((t5_tmp * t54_tmp * 0.0561F +
                                       t7_tmp * t66_tmp * 0.0561F) -
                                      t75_tmp * t82_tmp * 2.0F) /
                                     2.0F);
  t35_tmp = t18_tmp + t124_tmp * 0.165F;
  t81_tmp = (t16_tmp + t123_tmp * 0.165F) - 0.0475F;
  t104 = (-t16_tmp - t123_tmp * 0.165F) + 0.0475F;
  t174 = t104 * t104;
  t175 = 1.0F / t104;
  t104 = t35_tmp * t35_tmp;
  t106_tmp = t123_tmp * t131_tmp;
  t91_tmp = t16_tmp - t106_tmp * t120_tmp * 0.33F;
  t82_tmp = t124_tmp * t131_tmp;
  t120_tmp = t18_tmp - t82_tmp * t120_tmp * 0.33F;
  t108_tmp = F * (1.0F / sqrtf(t104 + t81_tmp * t81_tmp));
  t51_tmp = Tp * t174 * (1.0F / (t104 + t174));
  t104 = t35_tmp * (1.0F / t174);
  T[0] =
      t108_tmp * (t35_tmp * t91_tmp * 2.0F - t81_tmp * t120_tmp * 2.0F) / 2.0F -
      t51_tmp * (t175 * t91_tmp - t104 * t120_tmp);
  T[1] = t108_tmp *
             (t106_tmp * t35_tmp * t33_tmp * 0.66F -
              t82_tmp * t81_tmp * t33_tmp * 0.66F) /
             2.0F +
         t51_tmp * (t175 * (0.0F - t106_tmp * t33_tmp * 0.33F) +
                    t104 * (t82_tmp * t33_tmp * 0.33F));
}

/*
 * File trailer for LegConv.c
 *
 * [EOF]
 */
