/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * LegConv.c
 *
 * Code generation for function 'LegConv'
 *
 */

/* Include files */
#include "LegConv.h"
#include <math.h>

/* Function Definitions */
  /* LegConv */
  /*     T = LegConv(F,Tp,PHI1,PHI4) */
  /*     This function was generated by the Symbolic Math Toolbox version 23.2.
   */
  /*     2023-10-04 14:10:28 */
void LegConv(float F, float Tp, float phi1, float phi4, float T[2])
{
  float t100;
  float t102_tmp;
  float t108_tmp;
  float t120_tmp;
  float t123_tmp;
  float t124_tmp;
  float t131_tmp;
  float t16_tmp;
  float t174;
  float t175;
  float t18_tmp;
  float t33_tmp;
  float t34_tmp;
  float t35_tmp;
  float t36_tmp;
  float t51_tmp;
  float t52_tmp;
  float t5_tmp;
  float t64_tmp;
  float t77_tmp;
  float t7_tmp;
  float t81_tmp;
  float t82_tmp;
  float t91_tmp;

  t174 = cos(phi1);
  t5_tmp = cos(phi4);
  t175 = sin(phi1);
  t7_tmp = sin(phi4);
  t16_tmp = t174 * 0.095;
  t18_tmp = t175 * 0.095;
  t33_tmp = t174 * 0.0361;
  t34_tmp = t5_tmp * 0.0361;
  t35_tmp = t175 * 0.0361;
  t36_tmp = t7_tmp * 0.0361;
  t100 = t18_tmp - t7_tmp * 0.095;
  t51_tmp = (t5_tmp * 0.095 - t16_tmp) + 0.095;
  t52_tmp = t35_tmp - t36_tmp;
  t64_tmp = (t34_tmp - t33_tmp) + 0.0361;
  t77_tmp = t100 * t100 + t51_tmp * t51_tmp;
  t81_tmp = t174 * t100 * 0.19 + t175 * t51_tmp * 0.19;
  t82_tmp = t5_tmp * t100 * 0.19 + t7_tmp * t51_tmp * 0.19;
  t51_tmp = 1.0 / (t64_tmp + t77_tmp);
  t91_tmp = t51_tmp * t51_tmp;
  t100 = sqrt((t52_tmp * t52_tmp + t64_tmp * t64_tmp) - t77_tmp * t77_tmp);
  t102_tmp = 1.0 / t100;
  t108_tmp = (t36_tmp - t35_tmp) + t100;
  t120_tmp = atan(t51_tmp * t108_tmp) * 2.0;
  t123_tmp = cos(t120_tmp);
  t124_tmp = sin(t120_tmp);
  t131_tmp = 1.0 / (t91_tmp * (t108_tmp * t108_tmp) + 1.0);
  t120_tmp =
      (t35_tmp + t81_tmp) * t91_tmp * t108_tmp +
      t51_tmp *
          (t33_tmp - t102_tmp *
                         ((t174 * t52_tmp * 0.0722 + t175 * t64_tmp * 0.0722) -
                          t77_tmp * t81_tmp * 2.0) /
                         2.0);
  t33_tmp =
      (t36_tmp + t82_tmp) * t91_tmp * t108_tmp +
      t51_tmp * (t34_tmp -
                 t102_tmp *
                     ((t5_tmp * t52_tmp * 0.0722 + t7_tmp * t64_tmp * 0.0722) -
                      t77_tmp * t82_tmp * 2.0) /
                     2.0);
  t35_tmp = t18_tmp + t124_tmp * 0.19;
  t81_tmp = (t16_tmp + t123_tmp * 0.19) - 0.0475;
  t100 = (-t16_tmp - t123_tmp * 0.19) + 0.0475;
  t174 = t100 * t100;
  t175 = 1.0 / t100;
  t100 = t35_tmp * t35_tmp;
  t102_tmp = t123_tmp * t131_tmp;
  t91_tmp = t16_tmp - t102_tmp * t120_tmp * 0.38;
  t82_tmp = t124_tmp * t131_tmp;
  t120_tmp = t18_tmp - t82_tmp * t120_tmp * 0.38;
  t108_tmp = F * (1.0 / sqrt(t100 + t81_tmp * t81_tmp));
  t51_tmp = Tp * t174 * (1.0 / (t100 + t174));
  t100 = t35_tmp * (1.0 / t174);
  T[0] = t108_tmp * (t35_tmp * t91_tmp * 2.0 - t81_tmp * t120_tmp * 2.0) / 2.0 -
         t51_tmp * (t175 * t91_tmp - t100 * t120_tmp);
  T[1] = t108_tmp *
             (t102_tmp * t35_tmp * t33_tmp * 0.76 -
              t82_tmp * t81_tmp * t33_tmp * 0.76) /
             2.0 +
         t51_tmp * (t175 * (0.0 - t102_tmp * t33_tmp * 0.38) +
                    t100 * (t82_tmp * t33_tmp * 0.38));
}

/* End of code generation (LegConv.c) */
