/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * LegPos.c
 *
 * Code generation for function 'LegPos'
 *
 */

/* Include files */
#include "LegPos.h"
#include <math.h>

/* Function Definitions */
  /* LegPos */
  /*     POS = LegPos(PHI1,PHI4) */
  /*     This function was generated by the Symbolic Math Toolbox version 23.2.
    */
  /*     2023-10-04 14:10:26 */
void LegPos(float phi1, float phi4, float pos[2])
{
  float a;
  float b_a;
  float t14;
  float t15;
  float t2;
  float t3;
  float t4;
  float t5;
  float t6;
  float t8;

  t2 = cos(phi1);
  t3 = cos(phi4);
  t4 = sin(phi1);
  t5 = sin(phi4);
  t6 = t2 * 0.095;
  t8 = t4 * 0.095;
  t14 = t4 * 0.0361;
  t15 = t5 * 0.0361;
  t5 = t8 - t5 * 0.095;
  a = (t3 * 0.095 - t6) + 0.095;
  b_a = t14 - t15;
  t4 = (t3 * 0.0361 - t2 * 0.0361) + 0.0361;
  t5 = t5 * t5 + a * a;
  t4 = atan(1.0 / (t4 + t5) *
            ((t15 - t14) + sqrt((b_a * b_a + t4 * t4) - t5 * t5))) *
       2.0;
  t5 = t8 + sin(t4) * 0.19;
  t4 = (t6 + cos(t4) * 0.19) - 0.0475;
  pos[0] = sqrt(t5 * t5 + t4 * t4);
  pos[1] = atan2(t5, t4);
}

/* End of code generation (LegPos.c) */
