/*
 * File: LegPos.c
 *
 * MATLAB Coder version            : 23.2
 * C/C++ source code generated on  : 02-Oct-2023 13:13:57
 */

/* Include Files */
#include "LegPos.h"
#include <math.h>

/*
 * LegPos
 *     POS = LegPos(PHI1,PHI4)
 *
 * Arguments    : float phi1
 *                float phi4
 *                float pos[2]
 * Return Type  : void
 */
void LegPos(float phi1, float phi4, float pos[2])
{
  float a;
  float b_a;
  float t14;
  float t15;
  float t2;
  float t3;
  float t4;
  float t5;
  float t6;
  float t8;
  /*     This function was generated by the Symbolic Math Toolbox version 23.2.
   */
  /*     02-Oct-2023 20:34:34 */
  t2 = cosf(phi1);
  t3 = cosf(phi4);
  t4 = sinf(phi1);
  t5 = sinf(phi4);
  t6 = t2 * 0.085F;
  t8 = t4 * 0.085F;
  t14 = t4 * 0.02805F;
  t15 = t5 * 0.02805F;
  t5 = t8 - t5 * 0.085F;
  a = (t3 * 0.085F - t6) + 0.095F;
  b_a = t14 - t15;
  t4 = (t3 * 0.02805F - t2 * 0.02805F) + 0.03135F;
  t5 = t5 * t5 + a * a;
  t4 = atanf(1.0F / (t4 + t5) *
             ((t15 - t14) + sqrtf((b_a * b_a + t4 * t4) - t5 * t5))) *
       2.0F;
  t5 = t8 + sinf(t4) * 0.165F;
  t4 = (t6 + cosf(t4) * 0.165F) - 0.0475F;
  pos[0] = sqrtf(t5 * t5 + t4 * t4);
  pos[1] = atan2f(t5, t4);
}

/*
 * File trailer for LegPos.c
 *
 * [EOF]
 */
